name: Azure Functions Deploy

on:
  push:
    branches:
      - main  # Adjust to the branch you want to deploy from (e.g., main or master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: YOUR_AZURE_FUNCTION_APP_NAME  # Replace with your Azure Function App name
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # Set this secret in GitHub Settings
          package: ./
